// Created by Marco, 2022-04-24
//
// Issues 200 MarcoTokens to yours truly.


// Secret values from .env file
const {PRIVATE_KEY, API_KEY, CONTRACT_ADDRESS, WALLET} = process.env

// We use the Polygon Network MATIC testnet
const NETWORK = "maticmum"

// Contract ABI (application binary interface) generated by Hardhat
//
// This can be emitted to console via:
//          console.log(JSON.stringify(contract.abi));
const contract = require("../artifacts/contracts/Token.sol/MarcoToken.json");

async function main() {
    // Alchemy Provider
    // See: https://docs.ethers.io/v5/api/providers/api-providers/#AlchemyProvider
    const alchemyProvider = new ethers.providers.AlchemyProvider(network=NETWORK, API_KEY);
    // Signer
    const signer = new ethers.Wallet(PRIVATE_KEY, alchemyProvider);

    // Contract
    const marcoTokenContract = new ethers.Contract(CONTRACT_ADDRESS, contract.abi, signer);


    const tx = await marcoTokenContract.issueTokens(200);
    await tx.wait();

    const balance = await marcoTokenContract.totalSupply();
    console.log("Total supply: ", balance);
}

// Runs main()
main()
    .then(() => process.exit(0))
    .catch((error) => {
        console.error(error);
        process.exit(1);
    });
